version: "3.9"

services:
  bot:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
      - sqlite_data:/var/lib/sqlite
  tasks:
    build: .
    command: poetry run huey_consumer bot.tasks.huey
    env_file:
      - .env
    volumes:
      - sqlite_data:/var/lib/sqlite

volumes:
  sqlite_data:
  redis_data:
